#!/bin/sh

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e

cd "$(dirname "$0")/.."

if [ -f "Brewfile" ] && [ "$(uname -s)" = "Darwin" ]; then
  brew bundle check >/dev/null 2>&1  || {
    echo "==> Installing Homebrew dependencies"
    brew bundle
  }
fi

if [ -f "Gemfile" ]; then
  echo "==> Installing gem dependencies"
  bundle check --path vendor/gems >/dev/null 2>&1  || {
    bundle install --path vendor/gems --quiet --without production
  }
fi

if [ -f "composer.json" ]; then
  echo "==> Installing composer packages"
  php composer.phar validate >/dev/null 2>&1  || {
      php composer.phar install
  }
fi
