#!/bin/sh

# script/console: Launch a console for the application. Optionally allow an
#                 environment to be passed in to let the script handle the
#                 specific requirements for connecting to a console for that
#                 environment.

set -e

cd "$(dirname "$0")/.."

if [ -n "$1" ]; then
  # Use first argument as an environment name. Use this to decide how to connect
  # to the appropriate console.
  if [ "$1" = "production" ]; then
    flynn -c voicearchive -a voicetools-api run rails console
  elif [ "$1" = "staging" ]; then
    flynn -c voicearchive-staging -a voicetools-api run rails console
  else
    echo "Sorry, I don't know how to connect to the '$1' environment."
    exit 1
  fi
else
  # No argument provided, so just run the local console in the development
  # environment. Ensure the application is up to date first.
  script/update
  bin/rails console
fi
