#!/bin/sh

# script/server: Launch the application and any extra required processes
#                locally.

set -e

cd "$(dirname "$0")/.."

# Ensure everything in the app is up to date.
script/update

# Boot the app and any other necessary processes.

foreman start -e .env -f Procfile.dev
